application:
  web:
    prefix:
      public: /api/delivery
spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:delivery_db}
    username: ${DB_USERNAME:delivery_service}
    password: ${DB_PASSWORD:delivery_service_password}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: delivery-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
kafka:
  topics:
    product-reserved: ${KAFKA_TOPIC_ORDER_CREATED:product-reserved}
server:
  port: ${SERVER_PORT:8080}
  error:
    whitelabel:
      enabled: false
management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  metrics:
    distribution:
      slo:
        "[http.server.requests]": 1ms, 5ms, 10ms, 15ms, 25ms, 40ms, 60ms, 100ms, 200ms, 500ms,2s,5s,30s
  prometheus:
    metrics:
      export:
        enabled: true


#logging:
#  level:
#    org.springframework: TRACE
